<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Parameters_addBtn</name>
   <tag></tag>
   <elementGuidId>7ad4f666-4c90-4e88-9574-3cbd7c5d8d44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebarContentWrap']/div[2]/h6/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>95ae93fe-a8f9-4150-a486-1c10dc594b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-plus-circle</value>
      <webElementGuid>c822afec-c4c7-4b7f-95eb-1b28ca45409e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarContentWrap&quot;)/div[@class=&quot;tse-sidebar-param-list ng-star-inserted&quot;]/h6[@class=&quot;card-title text-uppercase&quot;]/a[@class=&quot;tse-sidebar-add-link float-right ng-star-inserted&quot;]/i[@class=&quot;fas fa-plus-circle&quot;]</value>
      <webElementGuid>b523598e-2ccd-489c-890b-dd2ed2546267</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarContentWrap']/div[2]/h6/a/i</value>
      <webElementGuid>f1647a85-3015-45a8-9f45-065458007124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h6/a/i</value>
      <webElementGuid>fa0c3dde-b4b3-447c-af55-a01835c7b9a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
