<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input File Parameter_textarea</name>
   <tag></tag>
   <elementGuidId>54dbdfd4-07da-4112-8150-10500d476e73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addFileParamInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addFileParamInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa02a21f-fe64-4dfa-b8ab-052fbbd691a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter Input File Param Name</value>
      <webElementGuid>ec282fa5-fddc-4612-8872-d4147d9b595f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e1a06735-156a-4461-bfee-cb678d7826cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addFileParamInput</value>
      <webElementGuid>a933cd14-a168-408a-971e-373544b8efc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Input File Param Name</value>
      <webElementGuid>291a60e6-65a0-472e-9521-8725fb0a27fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14b59057-b093-4fef-8d2b-22f9c6b63399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm tse-sidebar-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>2f92c0f1-8a74-4c3a-a82b-49cc3efa5094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addFileParamInput&quot;)</value>
      <webElementGuid>233adb55-38ca-4d26-b7e5-fb2f750c3c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addFileParamInput']</value>
      <webElementGuid>73d6474f-a77b-487c-9f0e-0f80869bec32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarContentWrap']/div[5]/div/input</value>
      <webElementGuid>6286cfcd-cf4c-4c2d-8e51-8ce8e06a70aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>eb6e44ff-78d7-4ecf-afb0-717e98c3e6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addFileParamInput' and @placeholder = 'Enter Input File Param Name' and @type = 'text']</value>
      <webElementGuid>7b2bf2df-b6ce-461a-8b8e-4ace765329be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
