<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Output File Parameter_textarea</name>
   <tag></tag>
   <elementGuidId>4df277db-effb-447f-8d87-bb305085f9f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addParamFileOutput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addParamFileOutput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eeafbf1b-8575-4e30-b4dd-3e2e2af347f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter File Output File Param Name</value>
      <webElementGuid>d86d7192-82a2-4409-9fad-73fc82fbda0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f05fabce-a69c-46d7-9891-25556fd7bc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addParamFileOutput</value>
      <webElementGuid>5230c9b6-3418-4bcf-852c-37beeac5548e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter File Output Param Name</value>
      <webElementGuid>fba08550-bded-41d4-85ea-c82b8616240b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d29fc909-3cf2-4c27-aa25-fd4b803f1414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm tse-sidebar-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a2dbb2e7-9790-402b-918e-1d29f9cf1c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addParamFileOutput&quot;)</value>
      <webElementGuid>73949bba-68cf-4207-9cca-174c5c4bca70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addParamFileOutput']</value>
      <webElementGuid>3051aa29-20c9-4725-a595-91ae8d196fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarContentWrap']/div[7]/div/input</value>
      <webElementGuid>71d275b2-a35d-4ba5-af79-dc3ede4d6017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>e92770f6-3113-422e-b450-5ddd3dcc5117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addParamFileOutput' and @placeholder = 'Enter File Output Param Name' and @type = 'text']</value>
      <webElementGuid>69cf718a-f8bc-4e8f-929b-b181be8fe230</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
