<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Output Parameter_textarea</name>
   <tag></tag>
   <elementGuidId>40a98c9e-74d2-47a4-b23f-897ea9a7f277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addParamOutput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addParamOutput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>140ba997-5cb4-43ce-9231-1a6e3e6bbed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter Output Param Name</value>
      <webElementGuid>72e30d75-6e9d-48e1-8f77-6752183ffecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dfc7d6af-8a91-4ce3-bcb8-d0e33ca89556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addParamOutput</value>
      <webElementGuid>beb35053-dfcb-4937-acd3-3776829a0aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Output Param Name</value>
      <webElementGuid>80e4fae0-e502-4f2e-8218-b7c04235b723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94867dc7-1970-4693-b048-0269b3f9217b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm tse-sidebar-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7f9b3e00-5c16-438c-bbad-221f6dea0fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addParamOutput&quot;)</value>
      <webElementGuid>45db7d07-6149-4738-853f-5e76c778b565</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addParamOutput']</value>
      <webElementGuid>453223cc-b20c-451c-8877-198c39fd97bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarContentWrap']/div[6]/div/input</value>
      <webElementGuid>bc581afe-44cc-4f36-86e8-b4e4882f1d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>32407fd5-64a3-49b2-8cdd-d7e70f1bc5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addParamOutput' and @placeholder = 'Enter Output Param Name' and @type = 'text']</value>
      <webElementGuid>70fda390-8a68-4722-9673-6bbad852a021</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
