<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Create new FDL</name>
   <tag></tag>
   <elementGuidId>f2c6ef03-c1e8-411e-a097-d6f6aa0346b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addFdlButton']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addFdlButton > i.fas.fa-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c2f5d2ae-9035-45b1-973a-c433bea71c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-plus</value>
      <webElementGuid>7eb13a06-0ca7-4950-a60a-7861e093baea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addFdlButton&quot;)/i[@class=&quot;fas fa-plus&quot;]</value>
      <webElementGuid>bafc813d-3883-4bae-ae90-d250eac1aa33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='addFdlButton']/i</value>
      <webElementGuid>8549c438-84b2-42ee-963a-092cf6c6a3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/button/i</value>
      <webElementGuid>5c40a4fe-b7b6-4b7f-aa92-92cb6eaba038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
