<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FDL Name</name>
   <tag></tag>
   <elementGuidId>72e417d5-e946-489f-a9d1-97838c1d58f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fdlNameInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fdlNameInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f54d9d30-7cc9-4eaa-bcf8-921e1e118d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c380fb3-f35e-4439-b208-06d423aac872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fdlNameInput</value>
      <webElementGuid>37310eda-e94f-4781-8285-f696bab9ee96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Form data lookup name</value>
      <webElementGuid>a77316e9-767a-4b28-a191-8ab5e6f70203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4bf7e71b-3b7b-4a97-8ab2-da256b247705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fdlNameInput&quot;)</value>
      <webElementGuid>24d39a8d-1e92-4611-81f7-e9979d64f76b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fdlNameInput']</value>
      <webElementGuid>0d5e2e7d-a1c0-428c-8b77-05a4b8d48820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='center-panel']/preview-script-rules/app-tabs/app-tab[5]/div/app-fdl-tab/div[2]/div/div[2]/div[2]/fieldset/div/div/input</value>
      <webElementGuid>65a2f024-5916-4e51-a656-8c37a8e88b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/fieldset/div/div/input</value>
      <webElementGuid>756211bb-3fa5-40b5-8ef3-fc7fed7e6656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fdlNameInput' and @placeholder = 'Form data lookup name']</value>
      <webElementGuid>3b058ffd-2be1-4866-abfb-5983ba885210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
