<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_Script Based</name>
   <tag></tag>
   <elementGuidId>a7f75ddf-0e5b-4daa-8488-fdfa87d06c95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='queryTypeScript']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#queryTypeScript</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d31a04d0-4993-4f0b-afd0-5e76f9a1a9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>queryTypeScript</value>
      <webElementGuid>aae81461-74cf-4caf-b80c-ccf3c177adc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4e1a118d-9256-4006-8396-b5b113de9daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>queryType</value>
      <webElementGuid>44651ddd-ec62-4caf-9071-02aa3741ac82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>scriptBased</value>
      <webElementGuid>3b9e319d-fc99-4b37-9a50-96fd18080a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3c6ae03f-d07f-40a6-9597-133b71c08a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;queryTypeScript&quot;)</value>
      <webElementGuid>406857e8-0c13-4969-a404-844803aa637a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='queryTypeScript']</value>
      <webElementGuid>2d093190-31d7-4154-941e-60e2a771790d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='center-panel']/preview-script-rules/app-tabs/app-tab[5]/div/app-fdl-tab/div[2]/div/div[2]/div[2]/fieldset/div[2]/label[2]/input</value>
      <webElementGuid>b2ab0f3e-a2c6-4fb8-9c59-83020e241c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>bc4b8fd0-114d-4a0a-a1c9-f0041e521dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'queryTypeScript' and @type = 'radio' and @name = 'queryType']</value>
      <webElementGuid>b2fa9f92-6c5c-4765-97db-4daa3f2b5b54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
