<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_SQL Based</name>
   <tag></tag>
   <elementGuidId>b5bc817c-6b80-46a7-823a-90afba25230b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='queryTypeSql']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#queryTypeSql</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d472f68-a525-4488-aee2-480ccc12415a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>queryTypeSql</value>
      <webElementGuid>df6ac84a-9776-4385-be7f-07c77a05a357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a9bfc959-fd7e-4c29-b68e-b2b85fed5fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>queryType</value>
      <webElementGuid>f1162166-206d-4eda-8995-19f040b794bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>sqlBased</value>
      <webElementGuid>c9f3cb89-eb84-4828-8e45-aaac66c10c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3eb8ca7f-7968-491b-b65e-61a4eb228b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;queryTypeSql&quot;)</value>
      <webElementGuid>b86cf116-e51f-4a20-b5f1-acf072068727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='queryTypeSql']</value>
      <webElementGuid>b4b32f50-004c-4152-be35-1e5375fed962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='center-panel']/preview-script-rules/app-tabs/app-tab[5]/div/app-fdl-tab/div[2]/div/div[2]/div[2]/fieldset/div[2]/label/input</value>
      <webElementGuid>b6805b1e-1d18-43a0-a70b-94a6867958cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/label/input</value>
      <webElementGuid>953316db-0bef-4c8e-901c-5dd419bd55ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'queryTypeSql' and @type = 'radio' and @name = 'queryType']</value>
      <webElementGuid>ec089092-a72a-4594-8f20-5b32e114f622</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
