<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DataSource</name>
   <tag></tag>
   <elementGuidId>1737c7b7-39bc-4e1b-ab1b-a497117d2dd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dataSourceNameSelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dataSourceNameSelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>74a0c2df-411e-49e4-a09d-bcb61e21f6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dataSourceNameSelect</value>
      <webElementGuid>fe608f12-213b-4b76-9524-9ed27ead295f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataSourceName</value>
      <webElementGuid>67953ef9-f4ba-4326-93ce-a3645bd8f642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>92ad1d5f-e5ee-4ba6-bee4-ea80019694e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>democonfigDataSource</value>
      <webElementGuid>af5a2886-af26-432e-98f8-804c2c955e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataSourceNameSelect&quot;)</value>
      <webElementGuid>4c41a03d-991c-47ce-9adf-4d8f8f85782f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dataSourceNameSelect']</value>
      <webElementGuid>70be8292-e454-421d-9620-9aeac6533c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='center-panel']/preview-script-rules/app-tabs/app-tab[5]/div/app-fdl-tab/div[2]/div/div[3]/div[2]/div/div/fieldset/div/div[3]/div/select</value>
      <webElementGuid>ac0d22e6-645c-460b-a97b-059fb32cffdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Source'])[1]/following::select[1]</value>
      <webElementGuid>130f7c8b-61f8-4bb8-828a-6e09353d2c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[3]/following::select[1]</value>
      <webElementGuid>0d41186e-255b-4d48-b9a2-37a6dff898a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Convert to Script Based FDL'])[1]/preceding::select[1]</value>
      <webElementGuid>838fd517-26ec-4e50-acb3-2644a4fafefd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Query'])[1]/preceding::select[1]</value>
      <webElementGuid>550920c8-9893-4114-93ac-d769b738c70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>03127711-7664-4536-99df-68248946bd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dataSourceNameSelect' and @name = 'dataSourceName' and (text() = 'democonfigDataSource' or . = 'democonfigDataSource')]</value>
      <webElementGuid>29a73b86-1899-4027-a443-25e90fd973d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
