<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Query</name>
   <tag></tag>
   <elementGuidId>da5c406b-92fd-4672-bebc-56ce30d2d2c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='scriptCodeEditor']/div/div/textarea)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.CodeMirror.cm-s-default.CodeMirror-focused > div > textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>18d8d0bf-5bfe-4686-baa3-76030e0dfc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>55457090-5803-44ac-98c3-036f626a9604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ad48e344-79e7-46be-8745-1a60980c365b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>58c742f4-9364-434c-9f47-0b0685e9a938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0af78303-0386-4801-b61c-5855d478ad78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;center-panel&quot;)/preview-script-rules[1]/app-tabs[1]/app-tab[5]/div[@class=&quot;pane&quot;]/app-fdl-tab[1]/div[@class=&quot;row tte-primary-display tte-template-properties&quot;]/div[@class=&quot;col-xs-12 tte-primary-panel scrolly&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-xs-9&quot;]/div[@class=&quot;col-xs-6&quot;]/div[@id=&quot;scriptCodeEditor&quot;]/div[@class=&quot;CodeMirror cm-s-default CodeMirror-focused&quot;]/div[1]/textarea[1]</value>
      <webElementGuid>3fd56182-debe-4a79-ac41-29b4b620d16a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='scriptCodeEditor']/div/div/textarea)[2]</value>
      <webElementGuid>809e06af-ae20-4702-96dd-4da2baee9bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/textarea</value>
      <webElementGuid>06faddc7-5db8-45a0-80a2-4b69f526ee7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
