<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Database</name>
   <tag></tag>
   <elementGuidId>e61de117-7117-4455-afa9-9e9bd7551f16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='catalogSelect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#catalogSelect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>catalogSelect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>catalog</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-block-level</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            -- Select a database--
                            _donotdelete
                            c19_201223_1130
                            c19_201228_0949
                            c19_201229_0919
                            c19_201229_1000
                            c19_201230_0935
                            c19_201231_1156
                            c19_201231_1425
                            c19_210104_0905
                            c19_210105_0909
                            c19_210105_0932
                            c19_210105_1145
                            c19_210106_1114
                            c19_210106_1339
                            c19_210107_1106
                            c19_210107_1624
                            c19_210120_1551
                            c19_210121_1518
                            c19_210122_1423
                            c19_210125_1151
                            c19_210126_0917
                            c19_210127_1420
                            c19_210128_1227
                            c19_210205_1003
                            c19_210209_1029
                            c19_5_1
                            c19_cv_201222_1425
                            c19_cv_201222_1527
                            c19_cv_201222_1637
                            c19_cv_201223_1130
                            c19_cv_201228_0949
                            c19_cv_201229_0919
                            c19_cv_201229_1000
                            c19_cv_201230_0935
                            c19_cv_201231_1156
                            c19_cv_201231_1425
                            c19_cv_210105_0909
                            c19_cv_210105_0932
                            c19_cv_210105_1145
                            c19_cv_210106_1114
                            c19_cv_210106_1339
                            c19_cv_210107_1106
                            c19_cv_210107_1354
                            c19_cv_210107_1624
                            c19_cv_210120_1551
                            c19_cv_210122_1423
                            clearview
                            clearviewapp
                            convergence
                            demo26698709
                            demo26711449
                            demo26713112
                            demo26780747
                            demo26781058
                            demo26795016
                            demo26802630
                            demo26854404
                            demo26859952
                            demo26861238
                            demo26862985
                            information_schema
                            mysql
                            new_schema
                            performance_schema
                            sakila
                            sys
                            westnash
                        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catalogSelect&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='catalogSelect']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmQueryBuilder']/fieldset/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='database'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='configDataSource'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Table'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name Column'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
