<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Browse_button</name>
   <tag></tag>
   <elementGuidId>8445d036-bc08-4e71-9931-844363276443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.file-upload-wrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.file-upload-wrap</value>
   </webElementProperties>
</WebElementEntity>
