<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search Base</name>
   <tag></tag>
   <elementGuidId>8da241dc-8b15-4950-b212-b16a1a0cb29a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fl-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fl-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d1463b7c-9128-4147-b093-c75bbb862319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-field-label</value>
      <webElementGuid>1f5e3ec2-35df-4833-972f-d30fa4237075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fl-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase</value>
      <webElementGuid>5f2ee200-cffe-41e7-b638-fe34e53b9062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>df8c6b71-3b85-4bf9-8762-cc8a4fdca67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search Base</value>
      <webElementGuid>69f39d5e-b4a5-47f2-bdca-0d2a19f43c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fl-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase&quot;)</value>
      <webElementGuid>0af7b900-35a5-47c7-90c5-d999618f3f19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='fl-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase']</value>
      <webElementGuid>4329ea7e-714a-42e8-a86f-04f54ba3787c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='g-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups:1']/tbody/tr[3]/td/div</value>
      <webElementGuid>de1d383d-504c-4fb4-a191-7088f295530a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available LDAP Groups'])[2]/following::div[1]</value>
      <webElementGuid>c17d749a-9889-4c17-9eca-c12bb6619fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assigned LDAP Groups'])[1]/following::div[2]</value>
      <webElementGuid>564bbfd3-67d7-47eb-8a13-1ff73ad5c5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Filter'])[1]/preceding::div[2]</value>
      <webElementGuid>545029d6-5a81-4917-851e-fb743eafb225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[2]/preceding::div[3]</value>
      <webElementGuid>901d03f9-3ee2-4c87-a613-3f785727f003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search Base']/parent::*</value>
      <webElementGuid>edbab3a1-c2cf-4992-a158-e37687e311a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[3]/td/div</value>
      <webElementGuid>c459958e-06ca-450d-bc7f-63fa6c606141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'fl-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase' and (text() = 'Search Base' or . = 'Search Base')]</value>
      <webElementGuid>48305979-277b-40c4-a539-0de0f576d79d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
