<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search Filter</name>
   <tag></tag>
   <elementGuidId>6cea91e5-c425-4bfd-98a9-3a6aceec417e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fl-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchFilter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fl-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchFilter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07ccadb5-8cd9-45b3-b81d-2469ef0963cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-field-label</value>
      <webElementGuid>86098606-5de1-4c00-82e3-ecb47827e788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fl-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchFilter</value>
      <webElementGuid>961770c2-136a-4caf-8f59-9a920bf23404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>9581a54e-dd7b-4a7f-8a19-aa4cb070b699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search Filter</value>
      <webElementGuid>597dacc5-1f0f-4544-a6aa-ffdbae8b0ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fl-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchFilter&quot;)</value>
      <webElementGuid>e5826661-2836-45a8-8ec2-88fab1be85fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='fl-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchFilter']</value>
      <webElementGuid>832a3ab6-cb57-4ca9-a9cf-c7353386d36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='g-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups:1']/tbody/tr[4]/td/div</value>
      <webElementGuid>5d69a2a5-2c9c-4ee0-b9d6-1f455b2c1196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Base'])[1]/following::div[2]</value>
      <webElementGuid>597ffb41-1fdd-492c-a104-c11d1f051125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available LDAP Groups'])[2]/following::div[3]</value>
      <webElementGuid>14b1ccf5-2aba-493b-b56c-6f047ca5452a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[2]/preceding::div[1]</value>
      <webElementGuid>3bd361f9-d2f6-4a78-b726-3c44bb629fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization Unit'])[2]/preceding::div[1]</value>
      <webElementGuid>c23b7cbe-dc28-4aa1-ad67-a9a0b2d9e1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search Filter']/parent::*</value>
      <webElementGuid>3bf03f8c-39c7-47a7-bab8-caab4562c3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[4]/td/div</value>
      <webElementGuid>952e8c52-ea23-4068-9c78-aa16f4b70c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'fl-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchFilter' and (text() = 'Search Filter' or . = 'Search Filter')]</value>
      <webElementGuid>9b089d3c-e61c-473a-9fc7-4f8d8ff05410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
