<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Base</name>
   <tag></tag>
   <elementGuidId>806d577c-1cee-423c-ba7b-d5df350e86a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fc-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fc-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c9b82de-eb1c-40c0-850e-30b2b0083d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase</value>
      <webElementGuid>b9cff949-3515-4b39-af3a-9a34e7aef0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4a68ebd-d3d7-4051-a400-f2a8bffaefea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FF_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchBase</value>
      <webElementGuid>86bafefd-dc21-4063-8f48-cdde730f6af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-text-control</value>
      <webElementGuid>fce20e90-22af-4270-99e6-647912c6fdf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase&quot;)</value>
      <webElementGuid>043ea9cc-3871-4be3-8eba-2e9750e3beed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fc-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase']</value>
      <webElementGuid>85f095e0-33ec-42a9-970d-9034fe7af98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase']/input</value>
      <webElementGuid>a3a4efd7-3f64-4bae-b4a0-ae47d5563ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>671c4b1f-01e4-44f0-8e7d-4e76b58d7b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fc-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchBase' and @type = 'text' and @name = 'FF_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchBase']</value>
      <webElementGuid>a6d17628-1bf3-434f-bce3-f3f0b517f348</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
