<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_User</name>
   <tag></tag>
   <elementGuidId>cb9c0ebf-835f-4c3c-af09-3af19b755a02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abba5c57-05c3-4928-9d74-94fc18f0bba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>26d9bd5d-1688-4d73-af2e-f7b79ab1fb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter_1</value>
      <webElementGuid>dc3db0c6-5b86-4fdc-a937-bedbad8f6bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter</value>
      <webElementGuid>89256f70-1c83-4d53-94ae-6b73cbbd27d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>(objectclass=user)</value>
      <webElementGuid>ccffbc0b-0ba1-4d4b-b776-ca2299973c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter_1&quot;)</value>
      <webElementGuid>9dee9db7-a45b-4556-87b9-94ec772f8aaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter_1']</value>
      <webElementGuid>c2bc851e-bac2-49d6-8a3f-5dcf93942411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchFilter']/input</value>
      <webElementGuid>69133163-8fb8-43e0-bb24-11773a9ad397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/input</value>
      <webElementGuid>391e8ac5-4819-45a4-8b92-88a0fcfae66a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter_1' and @name = 'radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter']</value>
      <webElementGuid>e38a0bef-d53d-4043-9cc1-90f0a42d88f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
