<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_Organization Unit</name>
   <tag></tag>
   <elementGuidId>ed314bcf-08d0-408f-8914-a9702f2c750b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10088ee0-b8df-4ac8-96d4-c3f60659d3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>facac673-2db8-4387-9c76-324847358435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter_2</value>
      <webElementGuid>91bedcb5-8c6b-4836-a4c2-be66ebca59ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter</value>
      <webElementGuid>28f37e8f-e44a-439a-bd5b-529ccb6a6f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>(objectclass=organizationalUnit)</value>
      <webElementGuid>93cdeb73-638d-4275-b89b-2877f99f0389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter_2&quot;)</value>
      <webElementGuid>74098634-823c-43ff-b462-d6d9faa63731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter_2']</value>
      <webElementGuid>8310c30f-109e-4180-b430-4bbbf9ce46b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-addAdGroupsDialog-ldapGroupsSelection-header-refreshGroups-newSearchFilter']/input[2]</value>
      <webElementGuid>8479f709-0264-4ad1-a139-9b961b48b6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>93e3ba76-f603-4629-84ff-751d4df7a498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter_2' and @name = 'radio_addAdGroupsDialog.ldapGroupsSelection.header.refreshGroups.newSearchFilter']</value>
      <webElementGuid>d75f26e6-3cef-4472-8ba1-104a123533ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
