<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Filter List_varible</name>
   <tag></tag>
   <elementGuidId>44e588b1-8f56-4db7-9e29-4db5322eaab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/app-variable-list[1]/div[@class=&quot;card tse-variable-list tse-variable-list-drop&quot;]/div[@class=&quot;card-header&quot;]/input[@id=&quot;varibleListFilter&quot;][count(. | //input[@id = 'varibleListFilter' and @placeholder = 'Start typing to filter list' and @type = 'search' and @class = 'form-control form-control-sm ng-untouched ng-pristine ng-valid']) = count(//input[@id = 'varibleListFilter' and @placeholder = 'Start typing to filter list' and @type = 'search' and @class = 'form-control form-control-sm ng-untouched ng-pristine ng-valid'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='varibleListFilter'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown-menu.show > app-variable-list > div.card.tse-variable-list.tse-variable-list-drop > div.card-header > #varibleListFilter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48a1f382-62f2-47d5-80d8-ec43476b279c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>varibleListFilter</value>
      <webElementGuid>d48d58fa-ae38-4e74-affa-dd55fad0adb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing to filter list</value>
      <webElementGuid>6a78c781-e739-47c1-aba0-af4bd32ca157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>8976f788-00db-4d86-adf3-72d6cac5b44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>6d4be1cc-5e10-4483-9898-45d928ab1319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/app-variable-list[1]/div[@class=&quot;card tse-variable-list tse-variable-list-drop&quot;]/div[@class=&quot;card-header&quot;]/input[@id=&quot;varibleListFilter&quot;]</value>
      <webElementGuid>78f97f65-ca26-4114-b1e8-7faed06886cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='varibleListFilter'])[2]</value>
      <webElementGuid>aef284bb-faee-4de2-90be-637719a70274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/app-variable-list/div/div/input</value>
      <webElementGuid>7ed1626f-ad9a-44d7-8e93-34d4c93af40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'varibleListFilter' and @placeholder = 'Start typing to filter list' and @type = 'search']</value>
      <webElementGuid>7f450726-3a83-4e7e-bf82-20cb6b621dd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
