<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bind Account Username</name>
   <tag></tag>
   <elementGuidId>d7621494-9908-4703-b680-7fa8de8fd611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fc-updateDialog-row3-col2-user']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fc-updateDialog-row3-col2-user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d111ec9-aae1-41a6-aee8-7c262cfabf10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc-updateDialog-row3-col2-user</value>
      <webElementGuid>c3181534-81e4-42ff-980e-b0b9b4166e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd66bbd1-e2ab-4099-93b3-6a5ddf512a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FF_updateDialog.row3.col2.user</value>
      <webElementGuid>b48e2231-559f-46fa-a466-ae8bc91a296c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-text-control</value>
      <webElementGuid>e0764661-b45b-468e-a7a3-9277dc74ea19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>231d9513-7360-4ad7-a65f-45d1c0b01cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc-updateDialog-row3-col2-user&quot;)</value>
      <webElementGuid>a4f5c1ff-75c0-4e2c-80bc-bd770fe81830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fc-updateDialog-row3-col2-user']</value>
      <webElementGuid>1d3e7f8d-fee5-4573-adaf-6108c7b2a7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-updateDialog-row3-col2-user']/input</value>
      <webElementGuid>d96d6e80-5c16-4736-809d-1589326cac02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/table/tbody/tr/td/table/tbody/tr/td[2]/div/table/tbody/tr/td/table/tbody/tr/td/div[2]/input</value>
      <webElementGuid>6582bb7a-069c-46aa-be85-448529a2ea60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fc-updateDialog-row3-col2-user' and @type = 'text' and @name = 'FF_updateDialog.row3.col2.user']</value>
      <webElementGuid>6bcdd901-4f44-4b1e-806a-e3191311fc06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
