<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Connection Name</name>
   <tag></tag>
   <elementGuidId>e0e92cb6-b763-4622-836b-1daaeec14fd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fc-updateDialog-row1-col1-connectionName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fc-updateDialog-row1-col1-connectionName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e2decba-44f3-41ec-9247-6043f2cc26d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc-updateDialog-row1-col1-connectionName</value>
      <webElementGuid>70e99706-aacb-4378-9efe-eed4ee2c68e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2365ee87-d386-4aaa-a7ff-913cda1aa36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FF_updateDialog.row1.col1.connectionName</value>
      <webElementGuid>d3f29024-e788-42e0-a688-9d2f904c5766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-text-control</value>
      <webElementGuid>6b428a71-d3a6-44d3-a56a-f07ee7120c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>85e53d05-fa5d-4bee-befa-a02787e1f493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc-updateDialog-row1-col1-connectionName&quot;)</value>
      <webElementGuid>fd3fefcb-63a0-4ec4-9b6c-177d8c65e590</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fc-updateDialog-row1-col1-connectionName']</value>
      <webElementGuid>9d75081a-fca5-4f4e-999c-88401dd922ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-updateDialog-row1-col1-connectionName']/input</value>
      <webElementGuid>fb94d7ff-8fc4-48b0-9017-00780d2bbb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>70079be4-e2f0-45ca-bffb-428f1d0f5dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fc-updateDialog-row1-col1-connectionName' and @type = 'text' and @name = 'FF_updateDialog.row1.col1.connectionName']</value>
      <webElementGuid>972cdce0-9b7b-479b-b75b-1f4b419dbd90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
