<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name Attribute</name>
   <tag></tag>
   <elementGuidId>0cdfb044-3c4d-4468-9397-26fbe03b28a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fc-updateDialog-row1-col2-userAttribute']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fc-updateDialog-row1-col2-userAttribute</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0886c33b-9470-4de3-8538-c1691cd10b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc-updateDialog-row1-col2-userAttribute</value>
      <webElementGuid>507095ce-9718-4783-8d53-d9dec069a435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f727c9b9-5738-4054-9454-880f80fc3318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FF_updateDialog.row1.col2.userAttribute</value>
      <webElementGuid>f6f7bf43-ea80-49fa-ab4f-e9867b7ba1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-text-control</value>
      <webElementGuid>d405d94f-f99a-4f1d-85bb-173be0bdb99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6016f3e9-cc6c-44bc-9309-ea5bbe70f424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc-updateDialog-row1-col2-userAttribute&quot;)</value>
      <webElementGuid>a625d483-ddec-4a11-aa12-d08f3ded687d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fc-updateDialog-row1-col2-userAttribute']</value>
      <webElementGuid>8960caa6-b22f-45d2-83dc-a52be5edb7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-updateDialog-row1-col2-userAttribute']/input</value>
      <webElementGuid>cdedd0b0-769d-422a-bd8f-27c6b34101e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/table/tbody/tr/td/table/tbody/tr/td/div[2]/input</value>
      <webElementGuid>721855d2-affc-430f-a6b6-5b4b862b8cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fc-updateDialog-row1-col2-userAttribute' and @type = 'text' and @name = 'FF_updateDialog.row1.col2.userAttribute']</value>
      <webElementGuid>2c55b27b-57aa-474d-9682-4e3648050bf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
