<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Prefix</name>
   <tag></tag>
   <elementGuidId>357cef06-60b2-4114-b672-fec45278b650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fc-updateDialog-row3-col1-ldapDomain']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fc-updateDialog-row3-col1-ldapDomain</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21b03e24-d559-4145-a5f7-25e48fa69dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc-updateDialog-row3-col1-ldapDomain</value>
      <webElementGuid>42ff0f23-763e-4974-8b19-44105ee3e346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdb72b6f-a459-456a-9e49-e00ffaa02c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FF_updateDialog.row3.col1.ldapDomain</value>
      <webElementGuid>c6d71188-cde8-4e67-b244-9a3b32fadf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-text-control</value>
      <webElementGuid>33bf783e-a00c-4cd1-a69c-3fd400389fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e057a5b7-1dde-4cd1-9b3c-7289ff469ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc-updateDialog-row3-col1-ldapDomain&quot;)</value>
      <webElementGuid>cc3e0691-cad7-4e7d-a45d-23a4d7228abe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fc-updateDialog-row3-col1-ldapDomain']</value>
      <webElementGuid>591f6f48-6cec-424f-9ec4-5f66546fe45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-updateDialog-row3-col1-ldapDomain']/input</value>
      <webElementGuid>9917681d-75cf-4c49-8953-cedcd2077128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div[2]/input</value>
      <webElementGuid>d96bfe3b-8d72-4773-809b-b946ba8b813e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fc-updateDialog-row3-col1-ldapDomain' and @type = 'text' and @name = 'FF_updateDialog.row3.col1.ldapDomain']</value>
      <webElementGuid>600cab26-646e-4936-96c2-38f8a908d8ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
