<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Base</name>
   <tag></tag>
   <elementGuidId>d52c92e3-8a05-472a-8083-35dedb1d6dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fc-updateDialog-row3-col1-searchBase']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fc-updateDialog-row3-col1-searchBase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6456f0a-4a99-47ee-8c47-b4ba7a564e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc-updateDialog-row3-col1-searchBase</value>
      <webElementGuid>7950408f-4a60-4b19-aeb8-e6acc123aeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b7741bc-d79c-427e-bb03-ccdd2d4380e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FF_updateDialog.row3.col1.searchBase</value>
      <webElementGuid>9d56bdc9-5871-418f-88d0-c4f6aa8524df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-text-control</value>
      <webElementGuid>56fa9d3a-cd0f-405d-84e3-5055bc5082c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ebfb0363-9bc0-4f93-afda-da9c7a9d99d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc-updateDialog-row3-col1-searchBase&quot;)</value>
      <webElementGuid>3d26d5cf-2dfb-4949-8957-9f806778180e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fc-updateDialog-row3-col1-searchBase']</value>
      <webElementGuid>4cfb387a-290c-4bc5-ad46-d904d54d188e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-updateDialog-row3-col1-searchBase']/input</value>
      <webElementGuid>5ac07057-e55c-4caa-8eda-024ade845203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/table/tbody/tr/td/table/tbody/tr/td/div/table/tbody/tr/td/table/tbody/tr/td/div[2]/input</value>
      <webElementGuid>7fb70ebf-6e9e-4693-ad14-8879fecec481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fc-updateDialog-row3-col1-searchBase' and @type = 'text' and @name = 'FF_updateDialog.row3.col1.searchBase']</value>
      <webElementGuid>dbbee202-bf02-402f-8055-fc70350ee5d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
