<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Suffix</name>
   <tag></tag>
   <elementGuidId>0fccb8d5-ea80-428f-bf00-233a3f6110b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fc-updateDialog-row3-col1-userSuffix']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fc-updateDialog-row3-col1-userSuffix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b06dcdeb-0d4f-4b6d-8df2-6947fd8a49e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc-updateDialog-row3-col1-userSuffix</value>
      <webElementGuid>de1db851-dabd-41b3-86f9-4022d9de936e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>913b6577-a5b9-43f8-ba46-294ce687fc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FF_updateDialog.row3.col1.userSuffix</value>
      <webElementGuid>ba25116c-ea2f-4bc3-af9c-1723d4e6671e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-text-control</value>
      <webElementGuid>d7ba8c5b-d6a9-4262-8ec9-395970be67c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5d644173-205d-42df-b2e4-027b5a4df787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc-updateDialog-row3-col1-userSuffix&quot;)</value>
      <webElementGuid>c975c595-1a8e-4a5e-bba3-52281be5c4e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fc-updateDialog-row3-col1-userSuffix']</value>
      <webElementGuid>2fc859ea-18f9-4f6f-afd3-e1b987759219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-updateDialog-row3-col1-userSuffix']/input</value>
      <webElementGuid>bed00976-0f1e-4011-bab6-5c0ebe863a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div[2]/input</value>
      <webElementGuid>15d9a92b-bed9-4aff-a41a-2ecbcbcc9db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fc-updateDialog-row3-col1-userSuffix' and @type = 'text' and @name = 'FF_updateDialog.row3.col1.userSuffix']</value>
      <webElementGuid>24221594-0885-4e54-9e8a-ccfd9e8a440c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
