<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Show List</name>
   <tag></tag>
   <elementGuidId>029f656d-ca00-4288-b432-24616deee2c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='showListButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#showListButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>959c71ef-0418-47a8-8103-5ba05c38e17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showListButton</value>
      <webElementGuid>90f31ae5-7fff-4abd-b50b-1cbf0ca533f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>bc5b8888-36a5-4cd7-9ea9-0b05a08ce877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to display query results</value>
      <webElementGuid>8b316835-de3d-43f8-a4ad-5190c530434a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-position</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>f46c8aef-96a5-4ea4-a767-cdaa433d98a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show List</value>
      <webElementGuid>23c0ca1b-b420-487e-b182-5a726086147f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showListButton&quot;)</value>
      <webElementGuid>d1305638-5598-48ed-9707-b8b3a1ac275a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='showListButton']</value>
      <webElementGuid>2d2764a2-8b04-419a-b4e6-dd5e059c33ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='optionListLinked']/div/div[2]/div/div/div/div/div[2]/div[3]/button[2]</value>
      <webElementGuid>2196c944-8d83-4a8b-be6a-b1584ac6ebb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Query Wizard'])[1]/following::button[1]</value>
      <webElementGuid>9cebb84c-5671-4278-91b4-3c9d63174441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press F11 for fullscreen editor'])[1]/following::button[2]</value>
      <webElementGuid>ccff10ca-a5a0-415c-8889-669958f781d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::button[3]</value>
      <webElementGuid>1cc87cf1-efcd-43b1-80f8-4d2cdf17e26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the Data Source where the option list values are stored.'])[1]/preceding::button[3]</value>
      <webElementGuid>82ebba29-f4c2-4a55-8c85-2a5a95ebb460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show List']/parent::*</value>
      <webElementGuid>98b9313f-69c6-494b-9e5b-5caf838e4176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>40711dd6-c74b-4728-bb4e-b8f7bb8b6d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'showListButton' and @title = 'Click to display query results' and (text() = 'Show List' or . = 'Show List')]</value>
      <webElementGuid>e98f7bbe-875d-4ba7-958d-2c9653392fe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
