<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_query</name>
   <tag></tag>
   <elementGuidId>5cd3a26e-e845-4e79-8483-aeb3a4e7f84f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;optionListLinked&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;span12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content-box padded-box&quot;]/div[@class=&quot;row-fluid&quot;]/div[@class=&quot;span7&quot;]/div[@class=&quot;CodeMirror cm-s-default CodeMirror-focused&quot;]/div[@class=&quot;CodeMirror-scroll&quot;]/div[@class=&quot;CodeMirror-sizer&quot;]/div[1]/div[@class=&quot;CodeMirror-lines&quot;]/div[1]/div[@class=&quot;CodeMirror-code&quot;]/div[1]/pre[1][count(. | //pre[(text() = '​' or . = '​')]) = count(//pre[(text() = '​' or . = '​')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>pre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>xpath=//form[@id='optionListLinked']/div/div[2]/div/div/div/div/div[2]/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>pre</value>
      <webElementGuid>757b5775-8759-479b-a45e-ea4f52ad02c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>d205a1ac-34bb-4aef-aedf-5447e2a2a27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optionListLinked&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;span12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;content-box padded-box&quot;]/div[@class=&quot;row-fluid&quot;]/div[@class=&quot;span7&quot;]/div[@class=&quot;CodeMirror cm-s-default CodeMirror-focused&quot;]/div[@class=&quot;CodeMirror-scroll&quot;]/div[@class=&quot;CodeMirror-sizer&quot;]/div[1]/div[@class=&quot;CodeMirror-lines&quot;]/div[1]/div[@class=&quot;CodeMirror-code&quot;]/div[1]/pre[1]</value>
      <webElementGuid>6c9b150e-76e7-4d65-9489-443dc71de544</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='optionListLinked']/div/div[2]/div/div/div/div/div[2]/div/div[6]/div/div/div/div/div[5]/div/pre</value>
      <webElementGuid>df54acff-4657-4d19-a3ba-3f5e5770e8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Query'])[1]/following::pre[1]</value>
      <webElementGuid>70671771-162c-4e36-8bd7-2aeecd0793e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Options Available'])[1]/following::pre[1]</value>
      <webElementGuid>01fc2cb0-b675-4cd2-8b0b-0a66ed5b7513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press F11 for fullscreen editor'])[1]/preceding::pre[1]</value>
      <webElementGuid>895e6eb1-0e24-4a33-ab6a-9a14c7f2ee14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//pre</value>
      <webElementGuid>27283807-0ac5-4433-b954-7506df317e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//pre[(text() = '​' or . = '​')]</value>
      <webElementGuid>84db140d-9c90-4c97-9be7-3724164ab825</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
