<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Secret</name>
   <tag></tag>
   <elementGuidId>5e63c60f-84ff-4698-8f9c-06fc9a0976aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fc-updateDialog-secret</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fc-updateDialog-secret']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b84cf65-0119-46a6-b4fe-b231aa920c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc-updateDialog-secret</value>
      <webElementGuid>53cc3117-187e-4146-a933-9516b540a279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>73083321-13e7-4e40-acfd-b33ac05c74ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b6ef108c-7eb5-4ba5-bdfa-4725706b3046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FF_updateDialog.secret</value>
      <webElementGuid>df1cff48-8f40-477f-b49c-f9a67883f1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-text-control</value>
      <webElementGuid>20a15e86-ea2e-43af-ab58-be41987a2efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7646aa10-7057-405f-872d-981c91b379d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc-updateDialog-secret&quot;)</value>
      <webElementGuid>93d2ade3-e59e-4b2e-a2cf-8667fd74ab22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fc-updateDialog-secret']</value>
      <webElementGuid>d3306937-e4ea-4aa4-ab4b-15c801c6af8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-updateDialog-secret']/input</value>
      <webElementGuid>ad99b3f3-efb9-449a-8315-b28d950a0d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/div[2]/input</value>
      <webElementGuid>a9f735a5-0f92-48ec-9eba-6b74e005adb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fc-updateDialog-secret' and @type = 'password' and @name = 'FF_updateDialog.secret']</value>
      <webElementGuid>d628ddb2-a6df-4341-9c3e-56779c2fc107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
