<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt _Duo Name</name>
   <tag></tag>
   <elementGuidId>79c84dcd-bb55-4326-9af9-bc6aee766d07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fc-updateDialog-duoName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fc-updateDialog-duoName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7601d10e-984b-4bcc-93b1-da8b1010e0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc-updateDialog-duoName</value>
      <webElementGuid>d1eab628-76d3-4d81-8d5d-34be610b5443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>921d4c3d-d70e-4d34-8d96-a2bffcf59275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FF_updateDialog.duoName</value>
      <webElementGuid>b72b6de8-a7c1-4be3-92a0-5e71650fe667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-text-control</value>
      <webElementGuid>054e9aad-7e09-4c76-9ca4-67d033bd8a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2f6b0445-f6fe-412d-921d-3cad730b946b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc-updateDialog-duoName&quot;)</value>
      <webElementGuid>a249ca19-f260-40d0-818c-9a3cb8a2a85a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fc-updateDialog-duoName']</value>
      <webElementGuid>abbb295a-66ad-4f64-ae21-a3d68ce172ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-updateDialog-duoName']/input</value>
      <webElementGuid>17597dad-9e74-44e6-b895-1610656b5b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d13d01f4-959a-4330-8835-54da2d2f8f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fc-updateDialog-duoName' and @type = 'text' and @name = 'FF_updateDialog.duoName']</value>
      <webElementGuid>779fa0b6-c214-493f-b9b6-a9fd4719329f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
