<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Integration Key</name>
   <tag></tag>
   <elementGuidId>98d9d2bb-b832-43c3-9b68-dc20a19a0594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fc-updateDialog-integrationKey</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fc-updateDialog-integrationKey']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ec49cf6-7e19-46c8-a913-39b65e26b50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc-updateDialog-integrationKey</value>
      <webElementGuid>7ca75d5c-e8b1-43cc-a1fa-475e1d4cd2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95c900e5-dee7-4612-8ce8-519af723441a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FF_updateDialog.integrationKey</value>
      <webElementGuid>cfa21862-39ec-46c3-9977-a539d023f224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-text-control</value>
      <webElementGuid>f10cb8c2-8e9c-4492-86e5-960e586721f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4251f421-9ec7-4a33-b1a5-5f10d9f5e8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc-updateDialog-integrationKey&quot;)</value>
      <webElementGuid>885770f0-4137-4272-b182-7a865d852e67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fc-updateDialog-integrationKey']</value>
      <webElementGuid>109ae55e-5219-4a54-82b0-ed1ffc3f19f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-updateDialog-integrationKey']/input</value>
      <webElementGuid>31c66721-3a8f-47bd-a411-c0961acc88c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div[2]/input</value>
      <webElementGuid>cb97bb39-2e64-42f3-b84d-93dc36a7f46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fc-updateDialog-integrationKey' and @type = 'text' and @name = 'FF_updateDialog.integrationKey']</value>
      <webElementGuid>93704aaf-7a8b-454e-8df7-bc295d242ff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
