<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kill Process</name>
   <tag></tag>
   <elementGuidId>cc20265b-a524-4dc5-87d4-a7042b54f9c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='threadKillLink0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#threadKillLink0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e251221-6ff7-4521-a08f-c2f0e07b0808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>killThread?killThreadForm=486</value>
      <webElementGuid>579051eb-4b13-46fb-8ca8-eb395ede79ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>threadKillLink0</value>
      <webElementGuid>b37db926-c059-4f98-93be-22fced5af758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thread_kill_id_link</value>
      <webElementGuid>810a2e4f-3b23-465d-90ae-f957091823bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form-id</name>
      <type>Main</type>
      <value>486</value>
      <webElementGuid>6af8ab87-82c8-4c99-9c19-4a608457132a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to kill process</value>
      <webElementGuid>2fc00b42-f079-43c1-8967-e368c1156c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kill Process</value>
      <webElementGuid>53a6e3db-6ed8-4614-84d8-298c1293d308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;threadKillLink0&quot;)</value>
      <webElementGuid>95ab7fc5-f9a2-40ac-b3e0-c52421d07a94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='threadKillLink0']</value>
      <webElementGuid>2b64e16d-a6a2-457f-9595-94b503033593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='monitorContent']/div[3]/div/table/tbody/tr/td[6]/a</value>
      <webElementGuid>1cb66e93-c685-461a-b676-b14b45f4f833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kill Process')]</value>
      <webElementGuid>5a14a6d9-bca5-46d6-b2e0-fcb086c8bd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='te'])[1]/following::a[1]</value>
      <webElementGuid>095512a1-cd32-4b3c-bc30-39f2f109e686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wait Action'])[1]/following::a[1]</value>
      <webElementGuid>0bdcc151-bd2e-4e4b-bcf5-ecb32c98daef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Working'])[1]/preceding::a[1]</value>
      <webElementGuid>30116d2a-6127-45c1-8d41-32dffee3c382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trinisys, LLC'])[1]/preceding::a[1]</value>
      <webElementGuid>156228c0-3778-4f74-b061-e5101d64c658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kill Process']/parent::*</value>
      <webElementGuid>5ddb2f68-fbe4-45b0-b163-a570fbfb76f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'killThread?killThreadForm=486')]</value>
      <webElementGuid>9d89de85-d7da-48ca-a6f7-d69d88f72ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>a3f4dbd4-bfcd-4d40-8774-f65a618c56c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'killThread?killThreadForm=486' and @id = 'threadKillLink0' and @title = 'Click to kill process' and (text() = 'Kill Process' or . = 'Kill Process')]</value>
      <webElementGuid>308a69cd-48c5-4635-ac47-7cbf4fbfd79b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
