<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Show Data Proccessors</name>
   <tag></tag>
   <elementGuidId>6e598558-c7bf-4096-bfd3-0fbf5cd4bc2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-eye</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8d5e49ff-e450-43a4-ae6d-acadfdadee64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-eye</value>
      <webElementGuid>14feb1de-f778-4fac-a3e9-8958634baaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container no-min-height&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;span12&quot;]/div[@class=&quot;page-header&quot;]/h1[1]/span[@class=&quot;pull-right&quot;]/a[@class=&quot;badge threads-badge tdes-action-tooltip&quot;]/i[@class=&quot;fas fa-eye&quot;]</value>
      <webElementGuid>11fd0a4d-0cb0-41e2-9558-7fde22cabfa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>450ccbd7-1ceb-49b1-bb6d-17ddbd890037</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
