<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_View_Hold</name>
   <tag></tag>
   <elementGuidId>84c7c59c-49ac-4de5-af12-aef06aa60455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='displayHoldLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#displayHoldLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a59cda78-1eaf-4dc2-bccf-ae0e43bc4c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a3ef627f-1787-4209-8b3d-f71823582aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayHoldLink</value>
      <webElementGuid>50a203ff-34dc-463e-8361-845db7ef9b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resource</name>
      <type>Main</type>
      <value>displayHoldForms</value>
      <webElementGuid>55f47d1d-af25-4d9e-be0d-9f5192dd8058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block view_queue_btn</value>
      <webElementGuid>ddcfae6d-6a5b-4ccf-8dd4-d389ba0fcd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Display hold contents</value>
      <webElementGuid>a91b93cb-201e-4fe6-aed6-71d0a29cd015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>3bd961d0-8b8b-428a-8414-c459c20c841f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayHoldLink&quot;)</value>
      <webElementGuid>c1f72903-8723-4c7d-b78b-3da672db24ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='displayHoldLink']</value>
      <webElementGuid>82c45205-86ca-4bb1-bb06-ae4bad928ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='monitorContent']/div/ul/li[2]/div/div[3]/button</value>
      <webElementGuid>9794a76e-f16f-4f33-8ee1-d4ffd787787d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure'])[2]/following::button[1]</value>
      <webElementGuid>a21030cd-4262-4c66-9cd4-fd9dfa21d235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Run Time'])[2]/following::button[1]</value>
      <webElementGuid>075265af-bb97-4c24-94d4-104eae18d96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[1]/preceding::button[1]</value>
      <webElementGuid>702cc542-0c92-48d5-8a4b-b5ff0a4dafa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='As of: 01/27/2022 02:19:44 PM'])[3]/preceding::button[1]</value>
      <webElementGuid>37ac9f5f-1b98-4d52-9cc7-5cf298557806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div[3]/button</value>
      <webElementGuid>ca1f2f61-988f-4e50-a61a-ad541d7ff0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'displayHoldLink' and @title = 'Display hold contents' and (text() = 'View' or . = 'View')]</value>
      <webElementGuid>53eb19cb-42de-4339-afd9-7569220245f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
