<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chkbox_comment</name>
   <tag></tag>
   <elementGuidId>309ef25b-84b8-43ee-af6b-6686846c509a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/app-root[1]/form[1]/div[1]/div[1]/app-actions-list[1]/div[1]/app-action-list-item[1]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/app-root[1]/form[1]/div[1]/div[1]/app-actions-list[1]/div[1]/app-action-list-item[1]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8eb9f6fd-178a-42e6-ac08-09bf7aab3c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d2aebcc2-6cdc-4dbf-a8eb-95097b6ca7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98b4bad3-cb40-4c87-8247-b50204d8950e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c77-4 ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>fd9facc8-ac0c-49ff-aef8-5e998905f40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb-1b11625a:18076036df4:7366</value>
      <webElementGuid>daa26a2d-a1cf-45ff-9118-a97e8e3082cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click to select action</value>
      <webElementGuid>8648a91a-1754-472e-9be2-ad809e9eeb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/form[1]/div[1]/div[1]/app-actions-list[1]/div[1]/app-action-list-item[1]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]</value>
      <webElementGuid>0c3a9250-61fc-4241-bf00-f5c018637b1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cb-1b11625a:18076036df4:7366']</value>
      <webElementGuid>89935aa9-9c99-4e4a-b900-ab077628bfb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actionListDiv']/app-action-list-item/div/div/div/div/div/input</value>
      <webElementGuid>d0c2d7e1-93db-4b65-a475-40c7fb1ddedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fc5df4f4-9cba-411d-b823-334920b87171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cb-1b11625a:18076036df4:7366' and @title = 'Click to select action']</value>
      <webElementGuid>23f3ca90-0f06-44ee-8a84-9fbcc8ef422f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
