<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SSN</name>
   <tag></tag>
   <elementGuidId>b206275e-a6d8-4798-9862-da15cbdfb903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='2f4fc567-8d9c-4b33-8a81-2221b1bc01c9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#2f4fc567-8d9c-4b33-8a81-2221b1bc01c9</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'ssn' and (text() = 'SSN' or . = 'SSN')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b0c4fa1-7d32-4bd2-9d17-98c9eecf9955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tte-ct-node tte-ct-text-field</value>
      <webElementGuid>f7d05632-25d2-4a86-b595-e7ea8c86e58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6560b6f9-f3c4-424f-984c-336b97eb15b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2f4fc567-8d9c-4b33-8a81-2221b1bc01c9</value>
      <webElementGuid>d1d932f9-d8e7-4771-91b9-0107f5253fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ssn</value>
      <webElementGuid>19ec799e-40ce-4908-b0d2-ccc0a87cd60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SSN</value>
      <webElementGuid>ce042d2c-4c4e-45a3-a124-acae49edc225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2f4fc567-8d9c-4b33-8a81-2221b1bc01c9&quot;)</value>
      <webElementGuid>d9cb24d0-1e6f-4dd4-8953-0dd1057cb51a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='2f4fc567-8d9c-4b33-8a81-2221b1bc01c9']</value>
      <webElementGuid>91d742a9-0362-4f4d-a314-f8e21d6d8d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='controlTreeWrap']/div[2]/fields-tree/div/div/ul/li[3]/div[2]</value>
      <webElementGuid>f8383cc4-4ab9-4678-a18b-4ed8d833b39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='last name'])[1]/following::div[5]</value>
      <webElementGuid>cf09f248-9e45-4648-aa7f-5c7bd719325b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='first name'])[1]/following::div[13]</value>
      <webElementGuid>77aab160-c852-40ef-adc5-428ec504b7ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::div[8]</value>
      <webElementGuid>7ae8b5fd-56a5-423a-b6bb-4836ddec1efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div[2]</value>
      <webElementGuid>a4c1aa6b-a8ce-4a35-bc56-e6bdc773b648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '2f4fc567-8d9c-4b33-8a81-2221b1bc01c9' and @title = 'ssn' and (text() = 'SSN' or . = 'SSN')]</value>
      <webElementGuid>bdcbf263-2b50-43b5-8329-5a4244e4c957</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
