<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Size_id</name>
   <tag></tag>
   <elementGuidId>23f6194d-38a5-431b-87ca-2cc7b713ad57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectCheck_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectCheck_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>594f934f-f677-4477-9a56-3a29aa043b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fab36d39-0c2f-4aff-95e1-dcf5380a9c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectCheck_0</value>
      <webElementGuid>6e57192e-0782-47ff-a554-fb67dce2a66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>fdfe44f0-62c5-4dc5-9d5c-587c08488561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>0a2503f2-7b2e-4ded-aefc-db01f70e1a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-list-name</name>
      <type>Main</type>
      <value>List</value>
      <webElementGuid>46639ccc-96e8-457f-8d8b-58dd73d7e766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectCheck_0&quot;)</value>
      <webElementGuid>336a37ec-a13e-49c3-a29a-31d226e7ff8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectCheck_0']</value>
      <webElementGuid>5707e1aa-fe5f-4d8d-b3fd-5e22b7cc88f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='optionListTable']/tbody/tr/td/input</value>
      <webElementGuid>a2326f31-e174-45f9-ad08-d2a89a49e019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>1d6e62c4-ace8-452e-9543-82ef34a9936c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'selectCheck_0' and @name = 'id']</value>
      <webElementGuid>293bbcff-b6ba-4178-b804-97d9a66000fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
