<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_PdfSignature</name>
   <tag></tag>
   <elementGuidId>87411f27-6dbd-4956-bdda-f09975967c74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='icRadio-82']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icRadio-82</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>477fc09a-ba40-4f5f-9463-8a07ebf451f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icRadio-82</value>
      <webElementGuid>82541299-4dec-40ea-aa1b-d944cd192cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>98ad65c2-de40-4cc1-8013-f9c5c2f351fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>implementationClass</value>
      <webElementGuid>d8338612-1d24-4427-add8-b9f820d5800a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>com.trinisys.tdes.scripting.digitalSig.GenerateKeyAction</value>
      <webElementGuid>cca80ef2-9fed-4fc4-a32f-b62391ed186e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icRadio-82&quot;)</value>
      <webElementGuid>48888158-3348-4400-a756-7c7229b66f80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='icRadio-82']</value>
      <webElementGuid>f6e9159e-7296-4e52-9bce-8818abff3bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='actionsListTable']/tbody/tr/td/input</value>
      <webElementGuid>1644601b-ff20-446c-b4fe-f5b5f734c234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>3adf82ae-4a89-47fd-9b4f-c082b8d21409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'icRadio-82' and @type = 'radio' and @name = 'implementationClass']</value>
      <webElementGuid>77228b41-89b8-4139-8253-ff318638e118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
