<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_Wait Action</name>
   <tag></tag>
   <elementGuidId>07659dff-d346-4cb0-9c21-581ebdb080a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='icRadio-116']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icRadio-116</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c546865-1353-440e-b62c-bed7277961aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icRadio-116</value>
      <webElementGuid>3a5b4d28-9037-4ed7-a80d-1224a8283818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8bbae34c-a7cb-4d15-b609-cb1c75f0880a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>implementationClass</value>
      <webElementGuid>5cce9222-c130-4326-a329-468fc5ccd3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>com.trinisys.tdes.scripting.actions.SleepAction</value>
      <webElementGuid>55762b6f-4773-48e8-a3d5-f1bc77021c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icRadio-116&quot;)</value>
      <webElementGuid>2d07ed51-a8a8-45d3-ae6b-b97fe7b1d2d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='icRadio-116']</value>
      <webElementGuid>ab8240b3-4d7d-493f-8178-3bc18b496eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='actionsListTable']/tbody/tr/td/input</value>
      <webElementGuid>7e43bc86-6511-4c93-ae83-11d7330e4f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>030ff3bc-4e42-4ef9-bc00-b323b8155633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'icRadio-116' and @type = 'radio' and @name = 'implementationClass']</value>
      <webElementGuid>c6fd3538-f38f-4dd4-9d5b-02110bb61aa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
