<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>40b0e7d0-ab52-4cfc-91bf-32a5efaa1fa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fc-credentialsDialog-servicePassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fc-credentialsDialog-servicePassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>900da9b2-965d-4774-9bdc-934d56639e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc-credentialsDialog-servicePassword</value>
      <webElementGuid>8b806169-2718-41f8-93c6-b7a4ffb577c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>57d608fa-5b2f-4f7e-b90a-5a4dc8cd4af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>773f3f6a-3364-4739-ba0d-b53adab1ca5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FF_credentialsDialog.servicePassword</value>
      <webElementGuid>5efce634-47d7-4382-8b6d-fab6d3f29449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tde-text-control</value>
      <webElementGuid>fa987a73-aa2d-4fec-9751-89d7dd844f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ec697db4-68ad-405e-bb19-c75531237286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc-credentialsDialog-servicePassword&quot;)</value>
      <webElementGuid>801b6ab0-4f5a-4d08-ba78-9cc638b6cc82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fc-credentialsDialog-servicePassword']</value>
      <webElementGuid>34d0c326-42bf-4439-97b1-fe099263a64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ff-credentialsDialog-servicePassword']/input</value>
      <webElementGuid>2fb8cc0f-aa55-422e-a59d-b4d18e9d97d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/table/tbody/tr[3]/td/div[2]/input</value>
      <webElementGuid>07c644c4-aa3a-4e04-83e5-96705355ec83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fc-credentialsDialog-servicePassword' and @type = 'password' and @name = 'FF_credentialsDialog.servicePassword']</value>
      <webElementGuid>ec4b848a-cd9d-4f32-8e2e-e342d8a141d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
